### PR TITLE
Increase automated reviewing for PRs

### PR DESCRIPTION
**Pull request by epage**

### CODE REVIEW

**Comment by epage** [comment]
Weird, why did appveyor not run?

**Comment by nastevens** [comment]
The project doesn't appear in appveyor - is the org allowed to share with appveyor? Also, I don't have admin permissions anymore on this project - could you please re-add me as an admin?

**Comment by epage** [comment]
Oh right, we need to add appveyor again due to the change

**Comment by epage** [comment]
I've authorized appveyor
https://ci.appveyor.com/project/epage/predicates-rs

**Pull request merged**
